df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.to_period('M')
monthly_cost_trend = df.groupby('Month')['Cost'].sum().reset_index()
monthly_cost_trend = monthly_cost_trend.sort_values(by='Month')
print('--- Monthly Cost Trend ---\n')
print(monthly_cost_trend)
service_cost = df.groupby('Service')['Cost'].sum().reset_index()
print('--- Total Cost by Service ---\n')
print(service_cost)
instance_type_cost = df.groupby('Instance_Type')['Cost'].sum().reset_index()
print('--- Total Cost by Instance Type ---\n')
print(instance_type_cost)
environment_cost = df.groupby('Environment')['Cost'].sum().reset_index()
print('--- Total Cost by Environment ---\n')
print(environment_cost)
service_environment_cost = df.groupby(['Service', 'Environment'])['Cost'].sum().reset_index()
print('--- Total Cost by Service and Environment ---\n')
print(service_environment_cost)